User.create!([
  {email: "user1@dummy", encrypted_password: "$2a$11$oJSs56Pqm3GC25hVq5grYeVgWlnDeAujs/OnU3ccfUk5QYILHshzG", reset_password_token: nil, reset_password_sent_at: nil, remember_created_at: nil, sign_in_count: 1, current_sign_in_at: "2016-06-17 03:06:00", last_sign_in_at: "2016-06-17 03:06:00", current_sign_in_ip: "127.0.0.1", last_sign_in_ip: "127.0.0.1", provider: nil, uid: nil},
  {email: "user2@dummy", encrypted_password: "$2a$11$mtON.71SHkBB1IHIq4pj4OMG.SSsbBWMDLZLRaFIBerQmrXB9j962", reset_password_token: nil, reset_password_sent_at: nil, remember_created_at: nil, sign_in_count: 1, current_sign_in_at: "2016-06-17 03:14:23", last_sign_in_at: "2016-06-17 03:14:23", current_sign_in_ip: "127.0.0.1", last_sign_in_ip: "127.0.0.1", provider: nil, uid: nil},
  {email: "user3@dummy", encrypted_password: "$2a$11$jU6eWkw6w4q9o66YFCC5AO.BQ7o7H1G5B07CjkQkDYXjyYTDRX/h6", reset_password_token: nil, reset_password_sent_at: nil, remember_created_at: nil, sign_in_count: 1, current_sign_in_at: "2016-06-17 04:11:02", last_sign_in_at: "2016-06-17 04:11:02", current_sign_in_ip: "127.0.0.1", last_sign_in_ip: "127.0.0.1", provider: nil, uid: nil}
])
Movie.create!([
  {title: "Warcraft: The Beginning ", year: 2016, synopsis: "The peaceful realm of Azeroth stands on the brink of war as its civilization faces a fearsome race of invaders: orc warriors fleeing their dying home to colonize another. As a portal opens to connect the two worlds, one army faces destruction and the other faces extinction. From opposing sides, two heroes are set on a collision course that will decide the fate of their family, their people, and their home. ", rating: 8.666666666666666, user_id: 1},
  {title: "Now You See Me 2", year: 2016, synopsis: "One year after outwitting the FBI and winning the public's adulation with their Robin Hood-style magic spectacles, The Four Horsemen resurface for a comeback performance in hopes of exposing the unethical practices of a tech magnate. The man behind their vanishing act is none other than Walter Mabry, a tech prodigy who threatens the Horsemen into pulling off their most impossible heist yet. Their only hope is to perform one last unprecedented stunt to clear their names and reveal the mastermind behind it all. ", rating: 5.0, user_id: 1},
  {title: "X-Men: Apocalypse", year: 2016, synopsis: "Since the dawn of civilization, he was worshipped as a God. Apocalypse, the first and most powerful mutant from Marvel's X-Men universe, amassed the powers of many other mutants, becoming immortal and invincible. Upon awakening after thousands of years, he is disillusioned with the world as he finds it and recruits a team of powerful mutants, including a disheartened Magneto, to cleanse mankind and create a new world order, over which he will reign. As the fate of the Earth hangs in the balance, Raven with the help of Professor X must lead a team of young X-Men to stop their greatest nemesis and save mankind from complete destruction. ", rating: 9.0, user_id: 2},
  {title: "Steve Jobs", year: 2015, synopsis: "Steve Jobs takes us behind the scenes of the digital revolution, to paint a portrait of the man at its epicenter. The story unfolds backstage at three iconic product launches, ending in 1998 with the unveiling of the iMac.", rating: 7.0, user_id: 2},
  {title: "Pirates of Silicon Valley", year: 1999, synopsis: "This is a semi-humorous biographical film about the men who made the world of technology what it is today, their struggles during college, the founding of their companies, and the ingenious actions they took to build up the global corporate empires of Apple Computer Corporation and Microsoft Inc. ", rating: 10.0, user_id: 2},
  {title: "Jobs", year: 2013, synopsis: "The story of Steve Jobs' ascension from college dropout into one of the most revered creative entrepreneurs of the 20th century.\r\n", rating: 8.0, user_id: 3}
])
Quote.create!([
  {text: "Our hope is destroyed; there is nothing to go back to. Is war the only answer?", movie_id: 1},
  {text: "Are you listening, horsemen? You will get what's coming to you. In ways you can't expect. ", movie_id: 2},
  {text: "Macintosh is not even a toy. It's a joke. IBM's now moved on to mini-DECs, and so should we. ", movie_id: 6},
  {text: "I never lost anything. It was stolen from me.", movie_id: 6}
])
Review.create!([
  {content: "Warcraft is astonishing. The visuals are ground breaking, the acting is very strong and the emotional involvement between the viewer and the movie is breath taking. The familiar zones from Warcraft universe are all and are built exactly how they are suppose to be built, every Warcraft fan will feel like home and on the brink of shedding tears.", rating: 10.0, user_id: 1, movie_id: 1, title: "GO SEE THIS MOVIE ! You will love every second of it !"},
  {content: "Anyone who has seen Christopher Nolan's cerebral masterwork in The Prestige will recall that a magic trick consists of three acts. Typically, this involves the 'setup' where the nature of the trick is explained, the 'performance' where the magician applies misdirection to fool the audience, and finally the 'effect' of the illusion on said audience. At no point will a magician reveal the secret behind the effect. So despite its critical consensus of style over substance, 2013's Now You See Me turned out to be a popular hit precisely due to the performance and misdirection applied. It was cheesy fun and at times nail bitingly good but we wanted to be fooled and we were.", rating: 5.0, user_id: 1, movie_id: 2, title: "NYSM2 is a literal and fatal misdirection with little in the way of fresh excitement"},
  {content: "X-Men: Apocalypse is absolutely amazing! The early reviewers don't seem to understand these characters and they don't understand this film. It sets a new precedent for comic book films in a world over-saturated with adaptations.", rating: 9.0, user_id: 2, movie_id: 3, title: "One of the best superhero films ever made leaves early reviewers clueless"},
  {content: "After watching the Movie i had no clue what Steve actually did, i mean i know some things, but i've learned nothing about his life after seeing this Movie. The only thing that this Movie brought to me was the Fact that he sucked as a Father and as a Human. Do i know why he did all this?...no.", rating: 7.0, user_id: 2, movie_id: 4, title: "Steve Jobs was entertaining.. yes, but it was difficult to follow the plot."},
  {content: "I loved this movie thoroughly. Many people may not \"get\" it properly due to their age, unfamiliarity with the characters, or general indifference to computers and stories involving them. For me, however, a computer enthusiast who was born in 1971, this movie is simply awesome!", rating: 10.0, user_id: 2, movie_id: 5, title: "Perfect nostalgia"},
  {content: "I actually thought this film would be bad. Like most other video game movies I thought this was going to be a massive flop and just suck. This movie broke the video game movie curse with style. WarCraft surprised me even though I am a WarCraft fan.\r\n\r\nIf there are sequels WarCraft could easily be this generations equivalent of The Lord of the Rings.", rating: 9.0, user_id: 2, movie_id: 1, title: "A great Fantasy flick"},
  {content: "I will watch again with my friends. ", rating: 8.0, user_id: 3, movie_id: 6, title: "Impressive film"},
  {content: "Good movie. But needs more introduction.", rating: 7.0, user_id: 3, movie_id: 1, title: "Not as bad as you think"}
])
